use_default_settings: true

server:
  port: 8080
  bind_address: 0.0.0.0
  secret_key: "replace_this_with_random_secret"
  base_url: "p01--searxng--24g85n86rvmw.code.run/"
  image_proxy: true

ui:
  static_use_hash: true
  theme_args:
    simple_style: auto

engines:
  - name: google
    disabled: false
  - name: duckduckgo
    disabled: false
  - name: bing
    disabled: false
  - name: wikipedia
    disabled: true

search:
  safe_search: 0
  autocomplete: "duckduckgo"
